/* =========================================================================
   UAT MODEL EXAM 2 — QUESTION DATA
   English Section: 55 questions / 60 minutes
   Math Section:    45 questions / 90 minutes
   All content below is original, written for this exam (not copied from
   any external source), and calibrated to be harder than Model Exam 1.
   ========================================================================= */

const PASSAGES = {
  p1: {
    title: "Passage 1",
    html: `
      <p><strong>(Paragraph 1)</strong> For most of the twentieth century, historians of science treated the laboratory notebook as a transparent window onto discovery&mdash;a faithful record of the moment an idea occurred to its author. Recent archival work complicates this picture considerably. Close comparison of dated entries against correspondence, travel records, and even weather reports has revealed that many celebrated notebooks were reorganized, and in some cases entirely recopied, well after the events they purport to document. The recopying was rarely fraudulent in intent; scientists routinely tidied their working papers before depositing them in institutional archives, smoothing false starts and abandoned tangents into a narrative that reads, in hindsight, as more linear than the actual process of inquiry ever was.</p>
      <p><strong>(Paragraph 2)</strong> The consequence is that historians who treat notebook dates as literal timestamps of insight risk reconstructing a history of science that overstates the role of sudden inspiration and understates the role of iterative revision. This is not merely a matter of correcting a few misattributed priority disputes. If the polished notebook is itself a retrospective composition, then the entire genre of "eureka narrative"&mdash;the story in which a single afternoon's observation resolves years of confusion&mdash;deserves scrutiny as a rhetorical convention rather than as reliable testimony. Some historians now argue that the notebooks should be read less as evidence of when a scientist thought something and more as evidence of how that scientist later wished the thinking to be remembered.</p>
    `
  },
  p2: {
    title: "Passage 2",
    html: `
      <p><strong>(Paragraph 1)</strong> The termite mounds of the African savanna have long been admired as marvels of unplanned engineering, their internal chimneys apparently regulating temperature and gas exchange without any termite ever consulting a blueprint. Recent fieldwork, however, suggests that the mounds are not static structures optimized once and left alone; colonies continuously renovate their mounds in response to seasonal shifts in humidity, and older mounds abandoned by one colony are frequently colonized and substantially rebuilt by another. The mound, in other words, functions less like a finished building and more like a slowly evolving manuscript, annotated and revised by successive occupants.</p>
      <p><strong>(Paragraph 2)</strong> This revision process complicates a long-standing assumption in the study of animal architecture: that a structure's form can be read as a direct expression of its builders' innate behavioral program. If successive termite colonies inherit and modify a partially built structure rather than starting from bare ground, then the mound's final geometry reflects an accumulated history of renovation choices made by multiple colonies over decades, not a single coherent plan executed by one generation. Researchers studying collective animal behavior have begun treating mounds as archives of layered decisions, a shift that requires considerably more patience than reading a mound as a snapshot of instinct.</p>
    `
  },
  p3: {
    title: "Cloze Passage",
    html: `
      <p>For most of the past decade, the regional archive <strong>____29____</strong> with a backlog of undigitized manuscripts. Two years ago, a newly hired conservator finally <strong>____30____</strong> that a piecemeal digitization schedule would never catch up with the rate of new acquisitions. A comprehensive digitization initiative <strong>____31____</strong> shortly afterward, funded by a private foundation grant. At this moment, a team of specialists <strong>____32____</strong> the most fragile eighteenth-century volumes before they are scanned. Archivists predict that by the close of next year, the institution <strong>____33____</strong> nearly the entire pre-1900 collection. The conservator remains convinced that the initiative <strong>____34____</strong> the long-standing accessibility problem that has frustrated researchers for years. Ever since the grant <strong>____35____</strong>, staff enthusiasm across the archive <strong>____36____</strong> considerably. In retrospect, had the foundation <strong>____37____</strong> the grant a decade earlier, the archive might never have accumulated so severe a backlog. Nearly every visiting scholar now <strong>____38____</strong> the newly searchable digital catalog.</p>
      <p style="color:var(--muted); font-size:0.9em; margin-top:10px;">Choose the option that best fits each numbered blank.</p>
    `
  },
  p4: {
    title: "Table: University Enrollment by Field, 2012 vs. 2023",
    html: `
      <p style="font-weight:600; margin-bottom:6px;">Undergraduate Enrollment Share and Average Class Size, Three Fields</p>
      <table class="data-table">
        <thead><tr><th>Field</th><th>2012 % Share</th><th>2023 % Share</th><th>2012 Avg. Class Size</th><th>2023 Avg. Class Size</th></tr></thead>
        <tbody>
          <tr><td>Computer Science</td><td>6%</td><td>22%</td><td>35</td><td>140</td></tr>
          <tr><td>Literature</td><td>14%</td><td>9%</td><td>28</td><td>19</td></tr>
          <tr><td>Civil Engineering</td><td>8%</td><td>11%</td><td>40</td><td>52</td></tr>
        </tbody>
      </table>
    `
  }
};

/* Each question: { id, passage (optional key into PASSAGES), text, options[4], answer (0-3) } */

const ENGLISH_QUESTIONS = [
  // ---- Passage 1: Q1-14 ----
  { id:1, passage:"p1", text:"Which choice best states the central claim of the passage?", options:["Laboratory notebooks are unreliable and should be excluded from historical research entirely.","Notebooks often reflect a retrospective tidying of discovery, which complicates their use as literal timestamps of insight.","Every historian of science has always doubted the accuracy of laboratory notebooks.","Scientists deliberately falsified their notebooks to win priority disputes."], answer:1 },
  { id:2, passage:"p1", text:"As used in paragraph 1, \"purport\" most nearly means:", options:["Prove conclusively","Claim or profess","Disprove entirely","Randomly select"], answer:1 },
  { id:3, passage:"p1", text:"The comparison of notebook entries to weather reports and travel records primarily serves to:", options:["Demonstrate a method by which historians uncovered discrepancies in notebook dating.","Prove that scientists always traveled before making major discoveries.","Suggest that weather affected the accuracy of scientific observation.","Argue that travel records are more reliable than laboratory notebooks."], answer:0 },
  { id:4, passage:"p1", text:"Which choice best describes the function of the second paragraph relative to the first?", options:["It contradicts the first paragraph's central claim.","It extends the first paragraph's observation to a broader implication for how history of science is written.","It shifts entirely to an unrelated topic in archival preservation.","It restates the first paragraph without adding new content."], answer:1 },
  { id:5, passage:"p1", text:"The author uses the phrase \"eureka narrative\" to refer to:", options:["A verified historical account of a scientific breakthrough.","A rhetorical convention in which sudden insight is credited with resolving prolonged confusion.","A type of laboratory notebook used exclusively in the nineteenth century.","A method for correcting priority disputes among scientists."], answer:1 },
  { id:6, passage:"p1", text:"The word \"tidied\" in paragraph 1 is used to suggest that scientists:", options:["Discarded their notebooks entirely before archiving them.","Reorganized their papers to appear more coherent than the actual process of inquiry.","Deliberately falsified their results to mislead future historians.","Refused to submit their notebooks to institutional archives."], answer:1 },
  { id:7, passage:"p1", text:"According to the passage, what is the primary risk of treating notebook dates as literal timestamps?", options:["Historians may overstate the role of sudden inspiration and understate iterative revision.","Historians may accidentally destroy irreplaceable archival material.","Scientists may be wrongly accused of plagiarism.","Notebooks may be physically damaged during examination."], answer:0 },
  { id:8, passage:"p1", text:"Which choice best captures the shift in how some historians now propose reading notebooks?", options:["As reliable, unedited testimony of the exact moment of discovery.","As evidence less of when a scientist thought something and more of how they later wished it to be remembered.","As legal documents with no historical value.","As purely fictional accounts with no bearing on actual events."], answer:1 },
  { id:9, passage:"p1", text:"The phrase \"more linear than the actual process of inquiry ever was\" suggests that real scientific inquiry is typically:", options:["Predictable and sequential from start to finish.","Marked by false starts and abandoned tangents rather than a straight path.","Entirely dependent on external funding sources.","Impossible to document in any written form."], answer:1 },
  { id:10, passage:"p1", text:"Based on the passage, the author would most likely agree that:", options:["All historical claims based on notebooks should be discarded outright.","A notebook's polish does not guarantee that its dates reflect the true timeline of discovery.","Scientists in the past never revised their working papers.","Priority disputes in science have all been resolved.", ], answer:1 },
  { id:11, passage:"p1", text:"Which choice best captures the relationship between \"recopying\" and \"fraud\" as the passage distinguishes them?", options:["The passage treats them as synonyms with no meaningful distinction.","Recopying was typically done for tidiness, not with intent to deceive, though it produces a similarly misleading record.","Fraud was the primary motive behind all recopied notebooks.","The passage argues recopying never occurred in any scientific archive."], answer:1 },
  { id:12, passage:"p1", text:"The overall tone of the passage is best described as:", options:["Dismissive of the value of archival research in the history of science.","Analytical and cautiously revisionist toward a long-standing historical assumption.","Outraged at scientists for concealing their discoveries.","Nostalgic for a simpler era of scientific record-keeping."], answer:1 },
  { id:13, passage:"p1", text:"Which choice, if true, would most directly undermine the passage's central argument?", options:["A large-scale study finding that notebook dates consistently match independent, contemporaneous corroborating records across many archives.","A study showing that some notebooks were recopied more than once.","A study showing that some scientists kept extremely messy notebooks.","A study showing that archivists sometimes misfiled historical documents."], answer:0 },
  { id:14, passage:"p1", text:"In context, \"scrutiny\" (paragraph 2) most nearly means:", options:["Immediate and unconditional acceptance.","Careful, critical examination.","Complete and total dismissal without review.","Casual and superficial acknowledgment."], answer:1 },

  // ---- Passage 2: Q15-28 ----
  { id:15, passage:"p2", text:"The passage is primarily concerned with:", options:["A comprehensive taxonomy of termite species found on the African savanna.","How the ongoing renovation of termite mounds by successive colonies complicates assumptions about animal architecture.","A comparison between termite mounds and human-engineered buildings.","The chemical composition of the soil used to build termite mounds."], answer:1 },
  { id:16, passage:"p2", text:"According to the passage, termite mounds are best characterized as:", options:["Static structures, optimized once and never altered again.","Continuously renovated structures shaped by successive occupants over time.","Structures built entirely by a single generation of termites in one season.","Structures with no relationship to seasonal humidity changes."], answer:1 },
  { id:17, passage:"p2", text:"The phrase \"slowly evolving manuscript\" (paragraph 1) suggests that a termite mound is:", options:["A fixed, unchanging document with no further additions.","Something continually annotated and revised over time by different builders.","A structure abandoned permanently after a single colony leaves it.","Entirely unrelated to the concept of gradual change."], answer:1 },
  { id:18, passage:"p2", text:"Which choice best describes the function of the second paragraph relative to the first?", options:["It disputes the engineering claims made in the first paragraph.","It explains a broader consequence for how animal architecture should be studied, based on the renovation pattern described in paragraph 1.","It shifts to an unrelated discussion of termite diet.","It argues that termite mounds have no engineering value whatsoever."], answer:1 },
  { id:19, passage:"p2", text:"According to the passage, why does the assumption that \"form directly expresses an innate behavioral program\" become complicated?", options:["Because termites do not actually build anything themselves.","Because successive colonies may inherit and modify a partially built structure rather than starting fresh, so the final form reflects layered history rather than one generation's plan.","Because mounds are entirely random in shape with no underlying cause.","Because researchers have never studied more than one mound."], answer:1 },
  { id:20, passage:"p2", text:"The word \"accumulated\" in paragraph 2, describing history, most nearly conveys that the mound's geometry:", options:["Appeared instantly and has remained unchanged.","Built up gradually through many decisions made over an extended period.","Was designed entirely at once by a single colony.","Has no connection to the mound's builders at all."], answer:1 },
  { id:21, passage:"p2", text:"Why do researchers now treat mounds as \"archives of layered decisions,\" according to the passage?", options:["Because a single colony's instinct fully explains the mound's final shape.","Because successive colonies' renovations accumulate over time, making the mound a record of many decisions rather than one.","Because termite mounds are never reused by more than one colony.","Because researchers no longer study termite behavior."], answer:1 },
  { id:22, passage:"p2", text:"Which choice best restates the passage's claim that studying mounds this way \"requires considerably more patience\"?", options:["Understanding a mound as a layered historical record takes longer than assuming it reflects one instinctive plan.","Termite mounds take decades to build regardless of interpretation.","Patience is irrelevant to the study of animal architecture.","Mounds can be fully understood within a single afternoon of observation."], answer:0 },
  { id:23, passage:"p2", text:"The overall tone of the passage is best described as:", options:["Skeptical of any scientific value in studying termite mounds.","Admiring and analytical, revising a long-standing assumption about animal architecture.","Purely descriptive with no interpretive claims about the research's significance.","Critical of researchers for studying termites at all."], answer:1 },
  { id:24, passage:"p2", text:"Based on the passage, which finding would most strengthen the claim that mounds reflect multi-colony history rather than single-generation instinct?", options:["Genetic and structural evidence showing that a mound's oldest chambers date to a different colony than its most recent additions.","Evidence that all termite colonies build in exactly the same style.","Evidence that termite mounds are abandoned and never reused.","Evidence that termites cannot sense humidity changes."], answer:0 },
  { id:25, passage:"p2", text:"In context, \"unplanned\" (paragraph 1) most nearly means:", options:["Deliberately designed according to a formal blueprint.","Arising without any single, centrally directed design.","Constructed entirely by human engineers.","Built only during a single termite's lifetime."], answer:1 },
  { id:26, passage:"p2", text:"Which choice best describes the passage's overall structure?", options:["It presents a widely held assumption, then complicates it with new research and its implications.","It presents two competing theories and refutes one outright.","It narrates a chronological history of termite mound construction.","It compares termite mounds unfavorably to modern buildings."], answer:0 },
  { id:27, passage:"p2", text:"The passage implies that a researcher who reads a mound's form as pure evidence of one colony's instinct would be:", options:["Making an assumption now complicated by evidence of ongoing multi-colony renovation.","Following the most up-to-date and well-supported interpretation.","Correct, since mounds are never reused by more than one colony.","Studying a completely different structure than a termite mound."], answer:0 },
  { id:28, passage:"p2", text:"Which choice best captures the meaning of \"innate\" as used in paragraph 2?", options:["Learned gradually through years of individual experience.","Inborn or naturally present from the start, rather than acquired.","Entirely dependent on external human instruction.","Related exclusively to seasonal humidity levels."], answer:1 },

  // ---- Cloze test Q29-38 ----
  { id:29, passage:"p3", text:"Blank 29:", options:["struggles","has struggled","had been struggling","will struggle"], answer:2 },
  { id:30, passage:"p3", text:"Blank 30:", options:["decides","decided","has decided","was deciding"], answer:1 },
  { id:31, passage:"p3", text:"Blank 31:", options:["launched","is launched","was launched","has been launched"], answer:2 },
  { id:32, passage:"p3", text:"Blank 32:", options:["stabilizes","is stabilizing","stabilized","will have stabilized"], answer:1 },
  { id:33, passage:"p3", text:"Blank 33:", options:["will have digitized","digitizes","digitized","was digitizing"], answer:0 },
  { id:34, passage:"p3", text:"Blank 34:", options:["will resolve","resolved","had resolved","was resolving"], answer:0 },
  { id:35, passage:"p3", text:"Blank 35:", options:["arrives","arrived","has arrived","was arriving"], answer:2 },
  { id:36, passage:"p3", text:"Blank 36:", options:["rises","rose","has risen","will rise"], answer:2 },
  { id:37, passage:"p3", text:"Blank 37:", options:["awarded","had awarded","will award","awards"], answer:1 },
  { id:38, passage:"p3", text:"Blank 38:", options:["praises","praised","has praised","will praise"], answer:0 },

  // ---- Sentence combining / concision Q39-48 (harder, denser originals) ----
  { id:39, text:"The auditing team, having spent nearly six weeks cross-referencing the subsidiary's ledgers against the parent company's consolidated statements, ultimately determined that the discrepancy stemmed not from fraudulent intent but from an outdated currency-conversion formula embedded in the accounting software.", options:["After six weeks of cross-referencing, auditors traced the discrepancy to an outdated currency-conversion formula rather than fraud.","Six weeks having been spent, the discrepancy from fraud not stemming, an outdated formula was determined by auditors.","The auditing team, cross-referencing for weeks, fraud was not found, an outdated formula being the cause determined ultimately.","Not from fraud but from a formula outdated in the software, the auditing team's six weeks determined the discrepancy's cause."], answer:0 },
  { id:40, text:"Whereas earlier drafts of the treaty had granted signatory nations broad discretion in interpreting the enforcement clause, the final version, revised after three rounds of contentious negotiation, narrowed that discretion considerably by specifying precise thresholds that would automatically trigger sanctions.", options:["Earlier drafts allowed broad discretion, but the final treaty narrowed it with automatic sanction thresholds.","Broad discretion having been granted earlier, narrowed considerably the final version's thresholds triggering sanctions automatically.","The final version, after negotiation, discretion narrowed by thresholds specifying sanctions triggered automatically was.","Contentious negotiation, three rounds having occurred, the treaty's discretion, broad earlier, was by thresholds narrowed."], answer:0 },
  { id:41, text:"It was only after the geologists had painstakingly matched isotope ratios across three separate rock formations, each collected from a different continent, that they felt confident asserting a shared volcanic origin dating back some sixty million years.", options:["After matching isotope ratios across three continents' rock formations, geologists confidently asserted a shared sixty-million-year-old volcanic origin.","Isotope ratios matched painstakingly, three continents' formations, confident the geologists felt of a shared origin sixty million years.","The geologists, matching ratios across continents, a shared origin sixty million years old, confidence they felt only after.","Only confident after matching, geologists' isotope ratios across formations asserted an origin volcanic shared sixty million years."], answer:0 },
  { id:42, text:"Despite the manufacturer's repeated assurances that the redesigned braking system had passed every safety benchmark required by federal regulators, independent engineers who reviewed the test data privately expressed doubts about whether the tests had adequately simulated wet-road conditions.", options:["Despite the manufacturer's assurances, independent engineers doubted whether the tests adequately simulated wet-road conditions.","The manufacturer assuring repeatedly, independent engineers, wet-road conditions simulated adequately, doubts privately expressed reviewing.","Federal regulators' benchmarks passed, doubts about simulation wet-road conditions engineers privately the data reviewing expressed.","Repeated assurances from the manufacturer, engineers independent reviewing data, doubts wet-road simulation adequately expressed privately."], answer:0 },
  { id:43, text:"The committee's final report, which synthesized testimony from over two hundred witnesses gathered across eighteen months of hearings, concluded that the infrastructure failure resulted from a convergence of deferred maintenance, understaffing, and an outdated inspection protocol rather than from any single decisive cause.", options:["The committee's report concluded that deferred maintenance, understaffing, and an outdated protocol together, not any single cause, caused the infrastructure failure.","Testimony synthesized from witnesses, the committee's report concluding a convergence, not any single cause, decisive.","Over two hundred witnesses, eighteen months of hearings, a convergence concluding the report of causes not single decisive.","The infrastructure failure, deferred maintenance and understaffing converging, the committee's testimony synthesized concluded protocol outdated."], answer:0 },
  { id:44, text:"One of the more persistent challenges facing municipal water authorities is reconciling the short-term political pressure to keep rates low with the long-term engineering necessity of funding gradual, preventive replacement of aging underground pipe networks before catastrophic failures occur.", options:["Municipal water authorities struggle to balance political pressure for low rates against the engineering need to fund preventive pipe replacement.","Reconciling pressure political short-term, engineering necessity long-term, municipal authorities' persistent challenge facing water rates.","Preventive replacement funding gradual, aging pipe networks, political pressure reconciling authorities municipal persistent.","Catastrophic failures occurring before, low rates kept, the challenge persistent authorities municipal water facing reconciling."], answer:0 },
  { id:45, text:"The primary reason the pilot program was extended for an additional fiscal year, rather than being either terminated or expanded to a full rollout, was that preliminary results, while promising, had not yet reached the statistical significance threshold the oversight board had set in advance.", options:["The pilot program was extended because its promising preliminary results had not yet reached the oversight board's preset significance threshold.","Terminated nor expanded, the pilot's reason extended for a year, statistical significance not yet reached preliminary.","The oversight board's threshold, set in advance, preliminary promising results reaching not yet the program extended.","Rather than expanded or terminated, results promising preliminary, the threshold significance the program's extension primary reason."], answer:0 },
  { id:46, text:"Having reviewed nearly a decade of climate data alongside migratory records for the species in question, the research team concluded that the birds' breeding range had shifted northward not gradually, as earlier models had predicted, but in several abrupt jumps correlated with specific extreme-weather years.", options:["After reviewing a decade of data, researchers found the birds' breeding range shifted northward in abrupt jumps tied to extreme-weather years, not gradually as predicted.","Migratory records alongside climate data, a decade nearly reviewed, the team's conclusion abrupt jumps correlated extreme-weather.","Not gradually but abruptly, the range breeding shifted northward, the team concluding years extreme-weather specific correlated.","The research team, reviewing records for nearly a decade, concluded shifted jumps abrupt correlated not gradual models earlier."], answer:0 },
  { id:47, text:"It should be understood by all tenants renewing their leases this cycle that the revised maintenance-fee structure, which allocates costs proportionally based on square footage rather than dividing them equally among units, will take effect at the start of the next billing quarter.", options:["Tenants renewing this cycle should know the new maintenance fee, allocated by square footage rather than equally, begins next billing quarter.","The revised structure, proportional square footage rather equal units, understood tenants renewing this cycle billing quarter next.","Equally dividing rather than proportionally, the fee structure revised, tenants understanding should be renewing this cycle.","Next quarter's billing, the maintenance fee proportional square footage, tenants renewing should this cycle understand structure revised."], answer:0 },
  { id:48, text:"The retrospective exhibition, curated jointly by two institutions that had rarely collaborated in the past, offered an unusually candid account of the artist's decades-long struggle with critical reception, juxtaposing celebrated early works against pieces that had been dismissed or ignored upon their original unveiling.", options:["The jointly curated retrospective candidly traced the artist's struggle with critical reception by juxtaposing celebrated and once-dismissed works.","Two institutions rarely collaborating, the exhibition's account candid decades-long struggle juxtaposing celebrated dismissed.","Critical reception's struggle decades-long, the artist's works celebrated and ignored juxtaposed institutions jointly curating.","Unusually candid, the retrospective's pieces dismissed originally unveiling juxtaposed celebrated early institutions two jointly."], answer:0 },

  // ---- Data interpretation Q49-55 ----
  { id:49, passage:"p4", text:"Which statement is best supported by the data when comparing all three fields from 2012 to 2023?", options:["Enrollment share declined in every field over the period shown.","Enrollment share increased in every field, though the size of the increase varied by field.","Enrollment share increased for Computer Science and Civil Engineering but decreased for Literature.","Average class size decreased in every field over the period shown."], answer:2 },
  { id:50, passage:"p4", text:"According to the table, which field experienced the largest percentage-point change (increase or decrease) in enrollment share?", options:["Computer Science","Literature","Civil Engineering","All three fields changed by the same amount"], answer:0 },
  { id:51, passage:"p4", text:"Which field is the only one shown to have experienced a decrease in average class size from 2012 to 2023?", options:["Computer Science","Literature","Civil Engineering","None of the fields experienced a decrease"], answer:1 },
  { id:52, passage:"p4", text:"Based on the table, which claim about the relationship between enrollment share and class size is best supported?", options:["Fields with larger increases in enrollment share tended to see larger increases in average class size.","There is no relationship between enrollment share and class size in any field shown.","Class size decreased in every field as enrollment share increased.","Computer Science had both the lowest 2023 enrollment share and the lowest 2023 class size."], answer:0 },
  { id:53, passage:"p4", text:"Which of the following CANNOT be determined from the data provided?", options:["The percentage-point change in enrollment share for Civil Engineering.","The exact number of students enrolled in Computer Science in 2023.","The direction of change in average class size for Literature.","The 2023 average class size for Computer Science."], answer:1 },
  { id:54, passage:"p4", text:"An enrollment-planning administrator reviewing this table might reasonably conclude that:", options:["Computer Science saw the most substantial combined shift toward higher enrollment share and larger class sizes, suggesting a need for more faculty hires.","Literature saw the most substantial growth in enrollment share between 2012 and 2023.","All three fields are on pace to reach 50% enrollment share within a decade.","Average class size is unrelated to enrollment share in any field."], answer:0 },
  { id:55, passage:"p4", text:"Which conclusion would require information beyond what the table provides?", options:["Whether Computer Science's percentage-point increase in enrollment share exceeded Civil Engineering's.","Whether the primary cause of Computer Science's enrollment growth was job-market demand rather than some other factor.","Whether Literature's average class size decreased between 2012 and 2023.","Whether Civil Engineering's 2023 class size exceeded its 2012 figure."], answer:1 },
];

const MATH_QUESTIONS = [
  // ---- Table-based Q1-4 ----
  { id:1, passage:"mtable", text:"What is the arithmetic mean of the exam scores shown in the table?", options:["66","68","70","72"], answer:1 },
  { id:2, passage:"mtable", text:"What is the median of the exam scores shown in the table?", options:["60","70","72","80"], answer:1 },
  { id:3, passage:"mtable", text:"What percentage of students scored strictly above 70? (Round to the nearest whole percent)", options:["18%","24%","28%","32%"], answer:2 },
  { id:4, passage:"mtable", text:"If four additional students each scored 90, how would the mean of the full data set change?", options:["It would decrease.","It would remain exactly the same.","It would increase.","It cannot be determined without recomputing every entry."], answer:2 },
  // ---- Algebra & functions Q5-20 (harder) ----
  { id:5, text:"Which of the following is an equation of the line perpendicular to 5x - 2y = 14 that passes through the point (4, -3)?", options:["y = (5/2)x - 13","y = (-2/5)x - 7/5","y = (-2/5)x + 1/5","y = (2/5)x - 23/5"], answer:1 },
  { id:6, text:"If f(x) = 4ax - 9 and f(5) = 51, what is the value of f(-3)?", options:["-63","-45","-27","-9"], answer:1 },
  { id:7, text:"For what value of k does the system below have NO solution?\n6x + ky = 15\n9x + 12y = 24", options:["6","8","9","12"], answer:1 },
  { id:8, text:"A vendor sells two types of notebooks: ruled and grid. A customer buys 7 ruled and 3 grid notebooks for a total of 970 birr. Another customer buys 4 ruled and 8 grid notebooks for 1120 birr. What is the cost of one grid notebook?", options:["70 birr","80 birr","90 birr","100 birr"], answer:2 },
  { id:9, text:"What is the product of the solutions to the equation (2x - 5)^2 - 9 = 0?", options:["4","5.25","5.5","6"], answer:0 },
  { id:10, text:"For the quadratic function g(x) = -2x^2 + 20x - 37, what is the maximum value of the function?", options:["11","13","15","17"], answer:1 },
  { id:11, text:"The sum of the roots of the equation 3x^2 - 21x + 30 = 0 is 7. What is the product of the roots?", options:["7","8","9","10"], answer:3 },
  { id:12, text:"A rectangular plot has an area of 220 square meters. The length exceeds twice the width by 2 meters. What is the perimeter of the plot?", options:["58 meters","62 meters","64 meters","70 meters"], answer:2 },
  { id:13, text:"For which value of c does the equation 4x^2 - 24x + c = 0 have exactly one distinct real solution?", options:["24","32","36","40"], answer:2 },
  { id:14, text:"Solve for x: (x + 2)/(x - 4) = (x - 8)/(x + 6)", options:["-4","-1","1","4"], answer:2 },
  { id:15, text:"What is the solution set for the equation 6/(x - 2) - 5/x = 1", options:["{5, -2}","{-5, 2}","{6, -1}","{-6, 1}"], answer:0 },
  { id:16, text:"The function f(x) = (x^2 - 25)/(x^2 - 3x - 10) has a vertical asymptote at:", options:["x = 5","x = -5","x = -2","x = 2"], answer:2 },
  { id:17, text:"Selam can complete a task in 10 hours. Working together, Selam and Bereket can complete the same task in 4 hours. How long would it take Bereket to complete the task alone?", options:["6 hours","6.2 hours","6.67 hours","7 hours"], answer:2 },
  { id:18, text:"What is the distance between the points (-7, 2) and (5, -3) on the coordinate plane?", options:["11","12","13","14"], answer:2 },
  { id:19, text:"A line segment has one endpoint at (-3, 5) and midpoint at (2, -1). What are the coordinates of the other endpoint?", options:["(-1, 2)","(7, -7)","(-8, 11)","(4, 2)"], answer:1 },
  { id:20, text:"What is the area of a triangle with vertices at A(-1, -2), B(5, -2), and C(1, 4)?", options:["12","15","18","20"], answer:2 },
  // ---- Continued algebra / exponential / geometry Q21-35 (harder) ----
  { id:21, text:"Two lines, y = (a/3)x - 5 and y = -4x + 9, are parallel. What is the value of a?", options:["-16","-12","12","16"], answer:1 },
  { id:22, text:"An item priced at 500 birr is increased by 30% and then decreased by 25%. What is the final price?", options:["475 birr","487.50 birr","500 birr","525 birr"], answer:1 },
  { id:23, text:"A jacket is on sale for 731 birr, which reflects a 22% discount off the original price. What was the original price?", options:["891.02 birr","920 birr","937.18 birr","950 birr"], answer:2 },
  { id:24, text:"A population of bacteria increases by 40% every hour. If the initial population is 500, what is the population after 4 hours?", options:["1,372","1,568","1,920.8","1,960"], answer:2 },
  { id:25, text:"In a survey, 65% of respondents were adults. Of the adult respondents, 40% preferred online shopping. What percentage of all respondents were adults who preferred online shopping?", options:["24%","26%","28%","30%"], answer:1 },
  { id:26, text:"What is the sum of all solutions to the equation |4x - 7| = 21", options:["-3.5","0","3.5","7"], answer:2 },
  { id:27, text:"What is the solution set for the equation |x - 6| = 2x", options:["{2, -6}","{2}","{6}","{6, -2}"], answer:1 },
  { id:28, text:"Which of the following represents the solution to the inequality |3x + 2| >= 11", options:["x <= -13/3 or x >= 3","-13/3 <= x <= 3","x <= -3 or x >= 13/3","-3 <= x <= 13/3"], answer:0 },
  { id:29, text:"What is the sum of the solutions to the equation |x^2 - 30| = 6", options:["0","6","12","24"], answer:0 },
  { id:30, text:"What is the equation of a circle with center (5, -2) and radius 7?", options:["(x - 5)^2 + (y + 2)^2 = 49","(x + 5)^2 + (y - 2)^2 = 49","(x - 5)^2 + (y + 2)^2 = 7","(x + 5)^2 + (y - 2)^2 = 7"], answer:0 },
  { id:31, text:"The equation x^2 + y^2 + 4x - 10y + 25 = 0 represents a circle. What is the radius of this circle?", options:["1","2","3","4"], answer:1 },
  { id:32, text:"A circle in the xy-plane has center (4, 0) and is tangent to the y-axis. What is the equation of the circle?", options:["(x - 4)^2 + y^2 = 4","(x - 4)^2 + y^2 = 16","x^2 + (y - 4)^2 = 16","(x + 4)^2 + y^2 = 16"], answer:1 },
  { id:33, text:"Which of the following points lies on the circle defined by (x - 3)^2 + (y + 4)^2 = 40?", options:["(3, -4)","(9, -2)","(-3, 4)","(9, -4)"], answer:1 },
  { id:34, text:"A projectile is launched from a platform 10 meters above ground. Its height, h, in meters, after t seconds is given by h(t) = -5t^2 + 30t + 10. What is the maximum height the projectile reaches?", options:["45 meters","50 meters","55 meters","60 meters"], answer:2 },
  { id:35, text:"Find the points of intersection of the parabola y = x^2 - 2x - 3 and the line y = x - 1. What is the sum of the x-coordinates of the intersection points?", options:["1","2","3","4"], answer:2 },
  // ---- Systems / rational / radical / more geometry Q36-45 (harder) ----
  { id:36, text:"If (x, y) is the solution to the system below, what is the value of 2x + y?\n4x + 3y = 26\n7x - 3y = 29", options:["10","12","14","16"], answer:1 },
  { id:37, text:"The graph of the line y = (-5/6)x + 8 is translated 3 units up and 6 units to the right. What is the y-intercept of the new line?", options:["11","13","16","19"], answer:2 },
  { id:38, text:"The value of an investment is modeled by the function V(t) = 2000(0.96)^t, where t is measured in years. Which statement is true?", options:["The initial investment is 0.96 birr.","The investment decreases by 4% each year.","The investment increases by 4% each year.","The investment decreases by 96% each year."], answer:1 },
  { id:39, text:"If g(x) = (6x - 5)/(3x + 7), for which value of x is g(x) undefined?", options:["-7/3","0","5/6","7/3"], answer:0 },
  { id:40, text:"Simplify the rational expression: (2x^2 - 5x - 12)/(x^2 - 16)", options:["(2x + 3)/(x + 4)","(2x - 3)/(x + 4)","(2x + 3)/(x - 4)","(x - 4)/(2x + 3)"], answer:1 },
  { id:41, text:"Solve for x: sqrt(3x + 4) - 2 = x - 4", options:["0 only","7 only","0 and 7","No solution"], answer:1 },
  { id:42, text:"Find the distance between the centers of the two circles defined by x^2 + y^2 - 6x + 8y = 0 and x^2 + y^2 + 10y - 24 = 0.", options:["3","sqrt(10)","6","sqrt(58)"], answer:1 },
  { id:43, text:"A tank can be filled by pipe A in 5 hours and emptied by pipe B in 8 hours. If both pipes are opened when the tank is one-quarter full, how many hours will it take to completely fill the tank?", options:["8","10","13.33","15"], answer:1 },
  { id:44, text:"What is the sum of the distinct solutions to the equation |x^2 - 9x| = 20", options:["2","9","18","20"], answer:2 },
  { id:45, text:"A solution is 20% acid. How many liters of pure acid must be added to 15 liters of this solution to create a new solution that is 50% acid?", options:["7 L","8 L","9 L","10 L"], answer:2 },
];

const MATH_TABLE_PASSAGE = {
  title: "Exam Score Frequency Table",
  html: `
    <p style="font-weight:600; margin-bottom:6px;">Frequency of scores on a recent placement exam</p>
    <table class="data-table">
      <thead><tr><th>Score</th><th>Frequency</th></tr></thead>
      <tbody>
        <tr><td>50</td><td>4</td></tr>
        <tr><td>60</td><td>6</td></tr>
        <tr><td>70</td><td>8</td></tr>
        <tr><td>80</td><td>5</td></tr>
        <tr><td>90</td><td>2</td></tr>
      </tbody>
    </table>
  `
};
PASSAGES.mtable = MATH_TABLE_PASSAGE;
